### ISSUE TITLE
u.fl and antenna suport?

### ISSUE THREAD

**Issue by lardAmungus** [fOmey/dirty_flasher#11]
the T-Display S3 comes with a u.fl connector on board but it seems as though the firmware doesn't support it. I've tried a few different antennas but with no luck. is this feature already supported and my antennas are not, or is this feature not available in the latest firmware? is it something that can be added?

also, thank you for the updates to the dirty flasher, this is my favorite GPIO module and has made others obsolete. the continued support is greatly appreciated.

**Comment by fOmey** [comment]
There is a small resistor that needs to be moved to use the IPEX connector:

![IPEX](https://github.com/fOmey/dirty_flasher/assets/5051561/09d1ccd5-51f4-41f7-a4a9-11d88fea3596)

In the image above, it's configured to use the internal antenna.

**Comment by lardAmungus** [comment]
it shall be moved, thank you!
