### ISSUE TITLE
Disapointed that i was the one to break it 

### ISSUE THREAD

**Issue by akracing** [fOmey/dirty_flasher#3]
Could not get the powershell file to flash for the life of me while using usb
if anyone else is having the same issue just open a command prompt in the tdisplay directory and run the following..

hold the boot button, plug in the usbc cabel, while still holding boot press the small reset button then let go of both

that should have you ready to flash

esptool --port COM19 flash_id

esptool --port COM19 erase_flash

esptool --chip esp32s3 --port COM19 --baud 460800 write_flash -z 0x0 esp32s3_marauder.ino.bootloader.bin 0x8000 esp32s3_marauder.ino.partitions.bin 0x10000 esp32s3_marauder.ino.bin

just change the port 

if i get around to adding some stuff from marauder ill ask to contribute

**Comment by fOmey** [comment]
What issues were you running into with power shell exactly?

**Comment by akracing** [comment]
it will either tell me that  Whoops: Check baudrate settings! or missing firmware

also, the evil portal, portal files arent in the bin 

was going to just build the source myself but your not sharing your source files

**Comment by fOmey** [comment]
You seem to be using an different baud in your example commands, power shell script uses a different baud (115200 or 921600) as listed in the readme. That may be the reason you were receiving that error? Glad to hear you sorted it out anyway.

As for the evil portal portal files, just drop them into the "EVILPORTAL" directory on your SD card.

**Comment by akracing** [comment]
ok i gotcha, i was just using a tdisplay flashed through usb have yet to do my diy flipper gpio board, just wired up a couple buttons to mess around with it

**Comment by akracing** [comment]
i did try to flash the endgame and the other one and both didnt work on the tdisplay, dont know if thats on purpose or if im totally missing why they fail but figured it doesnt hurt to mention it
