### ISSUE TITLE
Update Marauder.

### ISSUE THREAD

**Issue by b4k0s** [fOmey/dirty_flasher#8]
How do i update Marauder Firmware?

**Comment by thinktankbs** [comment]
Currently trying to update marauder via powershell, I get to the third prompt asking me to enter download mode, and gameover board appear to goto sleep but no update takes place

**Comment by thinktankbs** [comment]
> How do i update Marauder Firmware? 

Look up on tindie for the board you have, and the bottom will be update instructions
