### ISSUE TITLE
Way to update directly on a Mac / Unix ?

### ISSUE THREAD

**Issue by jcr-** [fOmey/dirty_flasher#9]
I'm on a Mac, and have the and although I've installed PowerShell, the dirty_flasher script won't work due to the Mac having unix-based serial devices (as the script expects COM ports). 

Is there a way to update from the bin files directly on the SD card (similar to how Marauder boards can do it)?

Chrome + https://fomey.github.io/dirty_flasher/ does work for me, so apparently it is possible. I'd just prefer to do it directly via cloning the GitHub repository if possible.

Thanks!

**Comment by fOmey** [comment]
No, the PowerShell script is likely going to be discontinued. as the web flasher is cross-compatible with all OS's.
